"""
MMDetection Default Config Template

This module provides the default MMEngine config template for MMDetection training.
The template is used by train.py to generate runtime config files.

Usage:
    from default_config import get_config_template
    config_str = get_config_template(
        model_name='faster-rcnn_r50_fpn',
        dataset_dir='/path/to/dataset',
        ...
    )
"""


def get_config_template(
    model_name: str,
    dataset_dir: str,
    work_dir: str,
    ann_file_train: str,
    ann_file_val: str,
    img_prefix: str,
    base_config: str,
    pretrained_url: str = None,
    # Training parameters
    epochs: int = 12,
    batch_size: int = 2,
    learning_rate: float = 0.02,
    warmup_iters: int = 500,
    val_interval: int = 1,
    img_scale: tuple = (1333, 800),
) -> str:
    """
    Generate MMDetection config content.

    Args:
        model_name: Model name (e.g., 'faster-rcnn_r50_fpn')
        dataset_dir: Path to dataset directory
        work_dir: Working directory for outputs
        ann_file_train: Path to training annotation file
        ann_file_val: Path to validation annotation file
        img_prefix: Path to images directory
        base_config: Base config file path
        pretrained_url: URL to pretrained weights
        epochs: Number of training epochs
        batch_size: Batch size per GPU
        learning_rate: Base learning rate
        warmup_iters: Number of warmup iterations
        val_interval: Validation interval (epochs)
        img_scale: Image scale (width, height)

    Returns:
        Config file content as string
    """
    # Calculate milestones based on epochs
    milestone1 = int(epochs * 0.67)
    milestone2 = int(epochs * 0.92)

    # Pretrained weights line
    load_from_line = f"load_from = '{pretrained_url}'" if pretrained_url else "load_from = None"

    return f'''# Auto-generated MMDetection config for {model_name}
# Generated by Vision AI Platform

_base_ = 'mmdet::detection/{base_config}'

# Dataset settings
data_root = '{dataset_dir}'

train_dataloader = dict(
    batch_size={batch_size},
    num_workers=4,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='CocoDataset',
        data_root=data_root,
        ann_file='{ann_file_train}',
        data_prefix=dict(img='{img_prefix}'),
        filter_cfg=dict(filter_empty_gt=False),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(type='Resize', scale={img_scale}, keep_ratio=True),
            dict(type='RandomFlip', prob=0.5),
            dict(type='PackDetInputs')
        ]
    )
)

val_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='CocoDataset',
        data_root=data_root,
        ann_file='{ann_file_val}',
        data_prefix=dict(img='{img_prefix}'),
        test_mode=True,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', scale={img_scale}, keep_ratio=True),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(type='PackDetInputs', meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'scale_factor'))
        ]
    )
)

test_dataloader = val_dataloader

# Evaluator
val_evaluator = dict(
    type='CocoMetric',
    ann_file='{ann_file_val}',
    metric='bbox',
    format_only=False
)
test_evaluator = val_evaluator

# Training schedule
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs={epochs}, val_interval={val_interval})
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')

# Optimizer
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='SGD', lr={learning_rate}, momentum=0.9, weight_decay=0.0001)
)

# Learning rate scheduler
param_scheduler = [
    dict(type='LinearLR', start_factor=0.001, by_epoch=False, begin=0, end={warmup_iters}),
    dict(type='MultiStepLR', by_epoch=True, milestones=[{milestone1}, {milestone2}], gamma=0.1)
]

# Runtime settings
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=50),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', interval=1, save_best='coco/bbox_mAP', rule='greater'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='DetVisualizationHook')
)

# Load pretrained weights
{load_from_line}

# Work directory
work_dir = '{work_dir}'

# Randomness
randomness = dict(seed=42, deterministic=False)
'''
